// The towns model — joins the three generated files into what the pages render.
//
//   gateway-ranked.json   which towns are within 40mi of a place BOUNDARY, and
//                         how far (negative = inside)          [157 places]
//   town-attributes.json  what each town IS — counts, tags, and the gate
//   place-geo.json        the places themselves: acreage, type [180 places]
//
// Attributes are generated by a slow Overpass crawl, so at any moment SOME towns
// have them and some don't. That is a normal state, not an error: a town without
// attributes yet is simply not shown in the directory, because the directory's
// entire job is to say what a town is. It still resolves on its own page.
import RANKED from "./gateway-ranked.json";
import ATTRS from "./town-attributes.json";
import GEO from "./place-geo.json";

const attrKey = (name, lat, lng) => `${name}|${lat.toFixed(3)},${lng.toFixed(3)}`;
export const townSlug = (name, st) =>
  (name + (st ? "-" + st : "")).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const ST_ABBR = { Alabama:"AL",Alaska:"AK",Arizona:"AZ",Arkansas:"AR",California:"CA",Colorado:"CO",Connecticut:"CT",Delaware:"DE",Florida:"FL",Georgia:"GA",Hawaii:"HI",Idaho:"ID",Illinois:"IL",Indiana:"IN",Iowa:"IA",Kansas:"KS",Kentucky:"KY",Louisiana:"LA",Maine:"ME",Maryland:"MD",Massachusetts:"MA",Michigan:"MI",Minnesota:"MN",Mississippi:"MS",Missouri:"MO",Montana:"MT",Nebraska:"NE",Nevada:"NV","New Hampshire":"NH","New Jersey":"NJ","New Mexico":"NM","New York":"NY","North Carolina":"NC","North Dakota":"ND",Ohio:"OH",Oklahoma:"OK",Oregon:"OR",Pennsylvania:"PA","Rhode Island":"RI","South Carolina":"SC","South Dakota":"SD",Tennessee:"TN",Texas:"TX",Utah:"UT",Vermont:"VT",Virginia:"VA",Washington:"WA","West Virginia":"WV",Wisconsin:"WI",Wyoming:"WY" };

// Built once at module load. The join is over ~5,000 rows, which is nothing, but
// doing it per request would be silly.
let CACHE = null;

function build() {
  const byKey = new Map();

  for (const [placeId, towns] of Object.entries(RANKED.places || {})) {
    const place = GEO.places[placeId];
    if (!place) continue;
    for (const t of towns) {
      const k = attrKey(t.name, t.lat, t.lng);
      if (!byKey.has(k)) {
        byKey.set(k, { name: t.name, lat: t.lat, lng: t.lng, serves: [] });
      }
      byKey.get(k).serves.push({
        id: placeId,
        name: place.name,
        type: place.type,
        acres: place.acres,
        // Sign carries the meaning: inside the boundary, or this far outside it.
        inside: t.inside,
        distanceMi: Math.abs(t.edgeMi),
      });
    }
  }

  const towns = [];
  for (const [k, t] of byKey) {
    const a = ATTRS.towns[k];
    // Nearest first — inside beats outside, which is what the sign gives us.
    t.serves.sort((x, y) => (x.inside === y.inside ? x.distanceMi - y.distanceMi : x.inside ? -1 : 1));

    const stateFull = stateFromServes(t.serves);
    towns.push({
      ...t,
      slug: townSlug(t.name, ST_ABBR[stateFull] || ""),
      state: stateFull || "",
      stateShort: ST_ABBR[stateFull] || "",
      place: a ? a.place : null,
      population: a ? a.population : null,
      counts: a ? a.counts : null,
      tags: a ? a.tags : [],
      // Undescribed yet vs described-and-rejected are different things, and the
      // directory needs to tell them apart.
      described: !!a,
      passes: a ? a.passes : false,
    });
  }
  return towns;
}

// The towns table has no state column; the places a town serves do.
function stateFromServes(serves) {
  for (const s of serves) {
    const g = GEO.places[s.id];
    if (g && g.state) return g.state;
  }
  return "";
}

export function allTowns() {
  if (!CACHE) CACHE = build();
  return CACHE;
}

// What the directory shows: described, and through the gate. A town still being
// crawled is absent rather than half-rendered.
export function directoryTowns() {
  return allTowns().filter((t) => t.described && t.passes);
}

export function townBySlug(slug) {
  return allTowns().find((t) => t.slug === slug) || null;
}

// "Towns inside the forest" — the editorial row. Genuinely derived, not curated:
// these sit within a boundary, which is a fact about them.
export function insideTowns(n = 3) {
  return directoryTowns()
    .filter((t) => t.serves[0] && t.serves[0].inside)
    .sort((a, b) => (b.counts?.lodging || 0) - (a.counts?.lodging || 0))
    .slice(0, n);
}

export const SORTS = {
  // Objective and unarguable, so it's the default.
  boundary: (a, b) => key(a) - key(b),
  stay: (a, b) => (b.counts?.lodging || 0) - (a.counts?.lodging || 0),
  small: (a, b) => (a.counts?.lodging || 0) - (b.counts?.lodging || 0),
};
function key(t) {
  const s = t.serves[0];
  if (!s) return Infinity;
  return s.inside ? -Math.abs(s.distanceMi) : s.distanceMi;
}

export function countsSummary() {
  const towns = directoryTowns();
  const places = new Set();
  for (const t of towns) for (const s of t.serves) places.add(s.id);
  return { towns: towns.length, places: places.size };
}
