// Park Buddy — gateway_towns SEED. Loads public/gateway-seed.json (every town within
// 150 mi of each park/forest, generated by scripts/build-gateway-full.mjs) into the
// gateway_towns table. Same reliable pattern as /api/destinations-seed: reads a
// committed file, replaces the park+forest rows, upserts. No live public API at runtime.
//
//   GET/POST /api/gateway-seed?token=INGEST_SECRET
//
// Env: SUPABASE_URL, SUPABASE_SERVICE_KEY, INGEST_SECRET
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

async function del(sb, key, type) {
  const r = await fetch(sb + "/rest/v1/gateway_towns?place_type=eq." + type, {
    method: "DELETE", headers: { apikey: key, Authorization: "Bearer " + key, Prefer: "return=minimal" },
  });
  if (!r.ok) throw new Error("delete " + type + " " + r.status);
}
async function insertBatch(sb, key, rows) {
  const r = await fetch(sb + "/rest/v1/gateway_towns", {
    method: "POST",
    headers: { apikey: key, Authorization: "Bearer " + key, "Content-Type": "application/json", Prefer: "return=minimal" },
    body: JSON.stringify(rows),
  });
  if (!r.ok) throw new Error("insert " + r.status + " " + (await r.text()).slice(0, 160));
}

export async function POST(request) {
  const sb = (process.env.SUPABASE_URL || "").replace(/\/+(rest(\/v1)?)?\/*$/i, ""), key = process.env.SUPABASE_SERVICE_KEY;
  if (!sb || !key) return Response.json({ error: "Set SUPABASE_URL and SUPABASE_SERVICE_KEY." }, { status: 500 });
  const { searchParams } = new URL(request.url);
  if (!process.env.INGEST_SECRET || searchParams.get("token") !== process.env.INGEST_SECRET) {
    return Response.json({ error: "unauthorized" }, { status: 401 });
  }
  const origin = new URL(request.url).origin;
  let data;
  try { data = await fetch(origin + "/gateway-seed.json", { cache: "no-cache" }).then((r) => r.json()); }
  catch (e) { return Response.json({ error: "Couldn't read gateway-seed.json: " + (e.message || e) }, { status: 500 }); }

  const rows = [];
  for (const pl of (data.places || [])) {
    for (const t of (pl.towns || [])) {
      rows.push({ place_id: pl.place_id, place_type: pl.place_type, name: t.name, bare_name: t.bareName, lat: t.lat, lng: t.lng, distance_mi: t.distanceMi, rank: t.rank, source: t.source });
    }
  }

  try { await del(sb, key, "national_park"); await del(sb, key, "national_forest"); }
  catch (e) { return Response.json({ error: "Delete failed: " + (e.message || e) }, { status: 500 }); }

  let inserted = 0; const errors = [];
  for (let i = 0; i < rows.length; i += 500) {
    const batch = rows.slice(i, i + 500);
    try { await insertBatch(sb, key, batch); inserted += batch.length; }
    catch (e) { errors.push(String(e.message || e)); } // keep going so one bad batch doesn't abort the seed
  }
  return Response.json({ ok: errors.length === 0, places: (data.places || []).length, totalRows: rows.length, inserted, errors: errors.slice(0, 5) });
}

export async function GET(request) { return POST(request); }
