import PinesFeed from "./PinesFeed";

// Pines — short vertical video for parks. Full spec in PINES.md. Full-screen feed of
// real, on-site, place-anchored clips. Phase 1a: feed + data model + pipeline scaffolding
// (capture/upload lands with the Cloudflare account).
const TITLE = "Pines — reels, but for the wild";
const DESC =
  "Short, real Adventures from the national parks — every one captured on-site, pinned to the exact place, next to today's live conditions. No stock, no fakes. Get early access.";

// Share cards: the OG image is generated by ./opengraph-image.js (branded, no asset needed).
export const metadata = {
  title: TITLE,
  description: DESC,
  alternates: { canonical: "/pines" },
  openGraph: { title: TITLE, description: DESC, url: "/pines", type: "website", siteName: "Park Buddy" },
  twitter: { card: "summary_large_image", title: TITLE, description: DESC },
};

export default function PinesPage() {
  return <PinesFeed />;
}
